language: cpp

compiler:
  - gcc
  - clang

cache: apt

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:henriquegemignani/uspgamedev
  - sudo apt-get update

install:
  - sudo apt-get install swig3.0 cmake
  - if [ "$CXX" = "g++" ]; then sudo apt-get install --force-yes g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

script:
  - cmake .
  - make libugdk
  - make ugdk_test
  - make ugdk_script_test
  - ./test/ugdk_test

notifications:
  email:
      - travis@uspgamedev.org
