language: cpp

compiler:
  - gcc
  - clang

cache: apt

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install swig2.0 python-dev libpng12-dev 
  - sudo apt-get install emacsen-common
  - wget http://uspgamedev.org/downloads/libs/ubuntu/cmake_2.8.11.2-1ubuntu5_amd64.deb http://uspgamedev.org/downloads/libs/ubuntu/cmake-data_2.8.11.2-1ubuntu5_all.deb
  - sudo dpkg -i cmake_*.deb cmake-data_*.deb
  - if [ "$CXX" = "g++" ]; then sudo apt-get install --force-yes g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

script:
  - cmake .
  - make libugdk
  - make ugdk_test
  - make ugdk_script_test
  - ./test/ugdk_test

notifications:
  email:
      - travis@uspgamedev.org
