language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ "${TRAVIS_OS_NAME:-linux}" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "${TRAVIS_OS_NAME:-linux}" = "linux" ]; then sudo add-apt-repository -y ppa:henriquegemignani/uspgamedev; fi
  - if [ "${TRAVIS_OS_NAME:-linux}" = "linux" ]; then sudo apt-get update; fi

install:
  - if [ "${TRAVIS_OS_NAME:-linux}" = "linux" ]; then sudo apt-get install swig3.0 cmake; fi
  - if [ "${TRAVIS_OS_NAME:-linux}" = "linux" -a "$CXX" = "g++" ]; then sudo apt-get install --force-yes g++-4.7; fi
  - if [ "${TRAVIS_OS_NAME:-linux}" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

script:
  - cmake .
  - make libugdk
  - make ugdk_test
  - make ugdk_script_test
  - ./test/ugdk_test

notifications:
  email:
      - henrique@uspgamedev.org
